<div id="menu-btn" class="menu">
        <div class="menu__line line-1"></div>
        <div class="menu__line line-2"></div>
</div>
<div id="menu-btn_arrow" class="menu">
        <div class="menu__arrow arrow_line-1"></div>
        <div class="menu__arrow arrow_line-2"></div>
</div>
<div class="container container-nav">
    <nav class="nav">
        <ul>
            <li><a href="#">Inicio</a></li>
            <li><a href="#">Servicios</a></li>
            <li><a href="#">Nuestro equipo</a></li>
            <li><a href="#">Portafolio</a></li>
            <li><a href="#">Contacto</a></li>
            <li><a href="#">Términos y condiciones</a></li>
        </ul>
    </nav>
</div>

<div class="logocontainer">
    <div class="logocontainer__mainlogo">
        <img src='<?php echo $this->getViewFileUrl('OmniPro_LoginMobile::images/Logo.svg'); ?>' alt="image-icon">
    </div>
</div>

<div class="letterlogo letterlogo-a">
    <img src='<?php echo $this->getViewFileUrl('OmniPro_LoginMobile::images/Fill 8.svg'); ?>' alt="image-icon">
</div>
<div class="letterlogo letterlogo-b">
    <img src='<?php echo $this->getViewFileUrl('OmniPro_LoginMobile::images/Fill 13.svg'); ?>' alt="image-icon">
</div>
<div class="letterlogo letterlogo-c">
    <img src='<?php echo $this->getViewFileUrl('OmniPro_LoginMobile::images/Fill 17.svg'); ?>' alt="image-icon">
</div>
<!--Pestañas-->
<div class="container">
    <div class="tab">
        <button class="tab-button current" id="tab-login-button">Ingreso</button>
        <button class="tab-button" id="tab-register-button">Registro</button>
    </div>
    <div class="tab-content active" id="tab-login">
        <form>
            <div class="tab-login__email">
                <p>EMAIL</p>
                <input type="email" id="email" placeholder="Email">
            </div>
            <div class="tab-login__pass">
                <p>CONTRASEÑA</p>
                <input type="password" id="password-login" placeholder="Contraseña">
            </div>
            
            <div class="subscriber">
                <input type="checkbox" name="sub">
                <p>Suscribirse al Newsletter</p>
            </div>
            <button type="submit">Ingreso</button>
            <a href="#" id="forgot-pass">Olvidaste la contraseña</a>

        </form>
    </div>
    <div class="tab-content" id="tab-register">
        <form onsubmit="return false">
            <div class="tab-register__name">
                <p>NOMBRE</p>
                <input type="text" id="firstname" placeholder="Nombre" required>
            </div>
            <div class="tab-register__lastname">
                <p>APELLIDO</p>
                <input type="text" id="lastname" placeholder="Apellido" required>
            </div>
            <div class="tab-register__email">
                <p>EMAIL</p>
                <input type="email" id="email-register" placeholder="Email" required>
            </div>
            <div class="tab-register__pass">
                <p>CONTRASEÑA</p>
                <input type="password" id="password-register" placeholder="Contraseña" required>
            </div>
            <button type="submit" id="register-button">Registro</button>
        </form>
    </div>
</div>
<div class="success" id="registered">
    <div class="success-text">
        <p>success</p>
    </div>
    <div class="success-icon">
    <img src='<?php echo $this->getViewFileUrl('OmniPro_LoginMobile::images/Path 21.svg'); ?>' alt="image-icon">
    </div>
</div>